Continue work on tests/python_to_cpp/pqmarkup.txt... (methods' call [.to_html(instr[...], outer_pos' i + 2)], functions' return type [to fix error C3779: 'Converter::to_html': a function that returns 'auto' cannot be used before it is defined])